language: ruby
bundler_args: --without development
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - rbx-2
addons:
  code_climate:
    repo_token: 71e004b35c45c89dfdd44c17a068166546cf01b1c64f7e9aa3eaf9ea9a61b42a
sudo: false
